const { fontFamily } = require('tailwindcss/defaultTheme');

module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#586076',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#dad7ff',
        'on-primary-fixed-variant': '#3323cc',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#4f46e5',
        'primary': '#3525cd',
        'primary-fixed': '#e2dfff',
        'on-primary-fixed': '#0f0069',
        'secondary-fixed': '#eaddff',
        'inverse-surface': '#2d3133',
        'outline': '#777587',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#4d44e3',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed': '#131b2e',
        'tertiary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#25005a',
        'inverse-primary': '#c3c0ff',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-secondary-container': '#fffbff',
        'on-surface-variant': '#464555',
        'tertiary': '#41485e',
        'on-tertiary-fixed-variant': '#3f465c',
        'surface': '#f7f9fb',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary-container': '#d4dbf5',
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#d2bbff',
        'secondary-container': '#8a4cfc',
        'surface-dim': '#d8dadc',
        'surface-container': '#eceef0',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'tertiary-fixed': '#dae2fd',
        'on-background': '#191c1e',
        'outline-variant': '#c7c4d8',
        'error-container': '#ffdad6',
        'secondary': '#712ae2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },

      fontFamily: {
        'body-md': ['Plus Jakarta Sans', ...fontFamily.sans],
        'headline-md': ['Plus Jakarta Sans', ...fontFamily.sans],
        'headline-lg-mobile': ['Plus Jakarta Sans', ...fontFamily.sans],
        'display-lg': ['Plus Jakarta Sans', ...fontFamily.sans],
        'body-lg': ['Plus Jakarta Sans', ...fontFamily.sans],
        'label-sm': ['Plus Jakarta Sans', ...fontFamily.sans],
        'headline-lg': ['Plus Jakarta Sans', ...fontFamily.sans],
        'label-md': ['Plus Jakarta Sans', ...fontFamily.sans],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      keyframes: {
        shake: {
          '10%, 90%': { transform: 'translate3d(-1px, 0, 0)' },
          '20%, 80%': { transform: 'translate3d(2px, 0, 0)' },
          '30%, 50%, 70%': { transform: 'translate3d(-4px, 0, 0)' },
          '40%, 60%': { transform: 'translate3d(4px, 0, 0)' },
        },
        float: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%': { transform: 'translate(20px, -30px) scale(1.05)' },
          '50%': { transform: 'translate(-10px, -15px) scale(0.95)' },
          '75%': { transform: 'translate(15px, -25px) scale(1.02)' },
        },
        'float-slow': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(-25px, 20px) scale(1.03)' },
          '66%': { transform: 'translate(15px, -20px) scale(0.97)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(24px) scale(0.98)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        shake: 'shake 0.4s cubic-bezier(.36,.07,.19,.97) both',
        float: 'float 12s ease-in-out infinite',
        'float-slow': 'float-slow 18s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
